services:
  redis:
    image: redis:7-alpine
    container_name: ignite-redis
    restart: always

  postgres:
    image: postgres:15
    container_name: ignite-postgres
    restart: always
    environment:
      POSTGRES_DB: senses_app_db
      POSTGRES_USER: senses_app_user
      POSTGRES_PASSWORD: aDMbB123kV
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: ignite-backend
    build: .
    # command: >
    #   gunicorn project_root.asgi:application
    #   -k uvicorn.workers.UvicornWorker
    #   --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /opt/ignite/staticfiles:/app/staticfiles
      - /opt/ignite/media:/app/media
      - /root/ignite-secrets/firebase-service-account.json:/app/firebase-service-account.json:ro
    depends_on:
      - redis
      - postgres
    restart: always

  celery:
    container_name: ignite-celery
    build: .
    command: celery -A project_root worker -l info
    env_file:
      - .env
    volumes:
      - /root/ignite-secrets/firebase-service-account.json:/app/firebase-service-account.json:ro
    depends_on:
      - redis
      - postgres
    restart: always

volumes:
  postgres_data:

