# Generated by Django 5.2.5 on 2026-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_processedstripeevent_chatsession_conversation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
