# Generated by Django 5.2.5 on 2026-02-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carry_forward_prompts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='has_ever_been_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
